language: node_js
node_js:
  - '10'
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
  firefox: '58.0'
services:
  - xvfb
before_script:
  - node ./ci_test/slimer/server.js &
install:
  - npm install
script:
  - npm run build
  - xvfb-run --server-args="-screen 0 1024x768x24" -a ./node_modules/.bin/slimerjs ./ci_test/slimer/index.js
  - xvfb-run --server-args="-screen 0 1024x768x24" -a ./node_modules/.bin/slimerjs ./ci_test/slimer/animations.js
  - node ./ci_test/slimer/compare.js
